(define (problem hanoi3)
  (:domain hanoi)
  (:objects peg1 peg2 d1 d2)
  (:init
   (smaller peg1 d1) (smaller peg1 d2)
   (smaller peg2 d1) (smaller peg2 d2)
   (smaller d2 d1)
   (clear d1) (clear d2)
   (on d1 peg1) (on d2 peg2)
  )
  (:goal (and (on d1 d2)))
  )