from .minecraft import render as minecraft_render
from .rearrangement import render as rearrangement_render
from .sokoban import render as sokoban_render
from .hanoi import render as hanoi_render
from .blocks import render as blocks_render
from .explodingblocks import render as exploding_blocks_render
from .doors import render as doors_render
from .tsp import render as tsp_render
from .slidetile import render as slidetile_render
from .tireworld import render as tireworld_render
from .snake import render as snake_render
from .searchandrescue import render as sar_render
from .slow_searchandrescue import render as slow_sar_render
from .posar import render as posar_render
from .myopic_posar import render as myopic_posar_render
from .sar_render_from_string_grid import sar_render_from_string_grid
from .hiking import render as hiking_render
from .maze import render as maze_render
from .navigation import render as navigation_render
from .visit_all import render as visit_all_render